// Code generated by "stringer -linecomment -type HoldRegister"; DO NOT EDIT.

package registers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Charge_Power_Percent_CMD-0]
}

const _HoldRegister_name = "Charge_Power_Percent_CMD"

var _HoldRegister_index = [...]uint8{0, 24}

func (i HoldRegister) String() string {
	if i < 0 || i >= HoldRegister(len(_HoldRegister_index)-1) {
		return "HoldRegister(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HoldRegister_name[_HoldRegister_index[i]:_HoldRegister_index[i+1]]
}
