// Code generated by "stringer -linecomment -type RegisterType"; DO NOT EDIT.

package registers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Input-0]
	_ = x[Hold-1]
}

const _RegisterType_name = "InputHold"

var _RegisterType_index = [...]uint8{0, 5, 9}

func (i RegisterType) String() string {
	if i < 0 || i >= RegisterType(len(_RegisterType_index)-1) {
		return "RegisterType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegisterType_name[_RegisterType_index[i]:_RegisterType_index[i+1]]
}
